export default theme => ({
  figure: {
    alignItems: 'center',
    backgroundColor: theme.palette.grey[200],
    borderRadius: 2,
    bottom: 0,
    display: 'flex',
    justifyContent: 'center',
    left: 0,
    margin: 0,
    overflow: 'hidden',
    padding: theme.spacing.unit * 2,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  img: {
    borderColor: theme.palette.background.paper,
    borderRadius: 2,
    borderStyle: 'solid',
    borderWidth: theme.spacing.unit,
    borderBottomWidth: theme.spacing.unit * 2,
    boxShadow: '0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23)',
    maxHeight: '100%',
    maxWidth: '100%',
    transition: 'box-shadow 0.3s cubic-bezier(.25,.8,.25,1)',
  },
  info: {
    alignItems: 'center',
    display: 'flex',
    paddingBottom: theme.spacing.unit * 3,
    paddingLeft: theme.spacing.unit * 2,
    paddingRight: theme.spacing.unit * 2,
    paddingTop: theme.spacing.unit * 3,
    position: 'relative',
    width: '100%',
  },
  preview: {
    position: 'relative',
  },
  price: {
    color: theme.palette.secondary.main,
    display: 'block',
    flex: 'none',
    fontSize: '1rem',
    minWidth: 0,
  },
  root: {
    cursor: 'pointer',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
    '&:hover': {
      '&>div>figure>img': {
        boxShadow: '0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)',
      },
    },
  },
  spacer: {
    paddingBottom: '100%',
    width: '100%',
  },
  title: {
    color: theme.palette.text.primary,
    display: 'block',
    minWidth: 0,
    flex: 1,
    fontSize: '1rem',
    paddingRight: theme.spacing.unit * 2,
  },
});
